language: php

services:
  - sqlite

env:
  - ILLUMINATE_VERSION=6.0.* PHPUNIT_VERSION=^8.3 TESTBENCH_VERSION=4.0.*

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=6.0.* PHPUNIT_VERSION=^8.3 TESTBENCH_VERSION=4.0.*

sudo: false

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer global require hirak/prestissimo --update-no-dev
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --prefer-dist
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install: travis_retry composer update --no-interaction --prefer-dist --no-suggest

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit --verbose